### ISSUE TITLE
kitchen test for centos 66 failing

### ISSUE THREAD

**Issue by brint** [rackspace-cookbooks/varnish#88]
It looks like Varnish fails to be restarted when using the libraries and vendor repo's on CentOS 6.6. To reproduce, run the following against master:

`kitchen test vendor-libraries-centos-66`

Trace:

```
           - enable service service[varnish]
       
           
           ================================================================================
           Error executing action `restart` on resource 'service[varnish]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/service varnish restart ----
           STDOUT: Stopping Varnish Cache: [FAILED]
           Starting Varnish Cache: [FAILED]
           STDERR: 
           ---- End output of /sbin/service varnish restart ----
           Ran /sbin/service varnish restart returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/varnish/libraries/varnish_install.rb
           
            62:         service 'varnish' do
            63:           supports restart: true, reload: true
            64:           action 'nothing'
            65:         end
            66:       end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/varnish/libraries/varnish_install.rb:62:in `install_varnish'
           
           service("varnish") do
             action [:nothing]
             updated true
             supports {:restart=>true, :reload=>true, :status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "varnish"
             enabled true
             pattern "varnish"
             declared_type :service
             cookbook_name "install_varnish"
           end
           
         * service[varnish] action restart
           
           ================================================================================
           Error executing action `restart` on resource 'service[varnish]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/service varnish restart ----
           STDOUT: Stopping Varnish Cache: [FAILED]
           Starting Varnish Cache: [FAILED]
           STDERR: 
           ---- End output of /sbin/service varnish restart ----
           Ran /sbin/service varnish restart returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/varnish/libraries/varnish_install.rb
           
            62:         service 'varnish' do
            63:           supports restart: true, reload: true
            64:           action 'nothing'
            65:         end
            66:       end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/varnish/libraries/varnish_install.rb:62:in `install_varnish'
           
           service("varnish") do
             action [:nothing]
             updated true
             supports {:restart=>true, :reload=>true, :status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "varnish"
             enabled true
             pattern "varnish"
             declared_type :service
             cookbook_name "install_varnish"
           end
           
         * service[varnish] action reload (up to date)
       
           - restart service service[varnishlog]
         * service[varnishncsa] action restart
           - restart service service[varnishncsa]
       
       Running handlers:
       [2015-09-04T20:06:50+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-09-04T20:06:50+00:00] ERROR: Exception handlers complete
       Chef Client failed. 27 resources updated in 159.060972897 seconds
       [2015-09-04T20:06:50+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-09-04T20:06:50+00:00] ERROR: Chef::Exceptions::MultipleFailures
       [2015-09-04T20:06:50+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <vendor-libraries-centos-66>.
>>>>>> Please see .kitchen/logs/vendor-libraries-centos-66.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------
```

**Comment by martinb3** [comment]
This should be fixed using #83 and #86. I just retested in vagrant and rackspace, and it passed. I'm going to mark this closed/fixed.
